# Welcome to Jekyll!
# Site settings

seo_title: >-      # Site title
  小宝的博客 | XiaoBao Blog
title: XiaoBao Blog    # Site nav title
description: >-     # Site description
  小宝的博客 | XiaoBao Blog ,这是小宝(@ShenBao)的个人博客，与你一起发现更大的世界。少抱怨，多思考，未来更美好！！！
keywords: >-        # Site keywords
  小宝的博客、XiaoBao Blog、shenbaoone@gmail.com, 沈宝, ShenBao,小宝,XiaoBao，知秋，@沈宝,@小宝,@ShenBao,@XiaoBao,@知秋，沈宝的博客,秋思浪人,QiusiLangren，秋思浪人的博客,ShenBao Blog,知秋的博客， 博客, 个人网站, 互联网, 前端，web developer,JavaScript,Js,ES5,ES6,React,Redux,React Native,SVN,Git,Gulp,WebPack,Fis3.
icon: "/img/config/author-100.png"


site_url: https://shenbao.github.io
baseurl: ""   # the subpath of your site, e.g. /blog
url: ""                           # site, e.g. http://example.com
site_author:  ShenBao
email: >-           # Site author email
  shenbaoone@gmail.com
creat_time: 2018

sidebar-is-show: true  # false
sidebar-about-icon: "/img/config/programmer.jpg"
sidebar-about-description: "少抱怨，多思考，未来更美好 ！"


# twitter_username: 
weibo_username:  ShenBaoPro
zhihu_username:  shenbao
github_username:  ShenBao
cnode_username:  ShenBao

disqus_username: ShenBao
# hypercomments_userid: 91931  # close

paginate: 5
paginate_path: "page:num"


markdown: kramdown # kramdown,redcarpet,rdiscount
kramdown:
input: GFM                            # use Github Flavored Markdown !important
highlighter: rouge
syntax_highlighter: rouge
highlight: true
#permalink: pretty
exclude: ["README.md","node_modules","package.json","package-lock.json","webpack.config.js","src","LICENSE.txt"]


plugins:
  - jekyll-feed
  - jekyll-paginate
